---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: jitsi
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:7.5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: grafana
              mountPath: /var/lib/grafana
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: jitsi
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: jitsi
spec:
  headers:
    stsSeconds: 63072000
    accessControlAllowOriginList:
      - "https://chaosdorf.de"
    accessControlAllowMethods:
      - "GET"
    accessControlMaxAge: 100
    addVaryHeader: true
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  namespace: jitsi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: jitsi-security@kubernetescrd
spec:
  tls:
    - hosts:
        - grafana.jitsi.freifunk-duesseldorf.de
      secretName: grafana-tls-prod
  rules:
    - host: grafana.jitsi.freifunk-duesseldorf.de
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: jitsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/jitsi/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s1
