---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: jitsi
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
      containers:
        - name: influxdb
          image: docker.io/influxdb:1.8.2
          ports:
            - containerPort: 8086
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: influxdb
              mountPath: /var/lib/influxdb
          env:
            - name: INFLUXDB_DB
              value: jitsi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: jitsi
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: jitsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/jitsi/influxdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s1
